baseURL = "https://enigma-soul.github.io/"
languageCode = "zh-CN"
title = "Blog - Enigma_Soul"
theme = "hextra"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    style = "github"


